//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FYP.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class tbl_Rating
    {
        public int R_Id { get; set; }
        [DisplayName("Rating")]
        [Required(ErrorMessage = "Required")]
        public Nullable<int> R_Name { get; set; }
        public Nullable<int> H_Id { get; set; }
    
        public virtual tbl_Hostel_Detail tbl_Hostel_Detail { get; set; }
        public virtual tbl_Rating tbl_Rating1 { get; set; }
        public virtual tbl_Rating tbl_Rating2 { get; set; }
    }
}
