//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FYP.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class tbl_User_info
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbl_User_info()
        {
            this.tbl_Hostel_Booking = new HashSet<tbl_Hostel_Booking>();
            this.tbl_Hostel_Detail = new HashSet<tbl_Hostel_Detail>();
        }
    
        [DisplayName("User ID")]
        public int U_Id { get; set; }
        [DisplayName("Image")]
        
        public string U_Image { get; set; }
        [DisplayName("Name")]
        [Required(ErrorMessage = "Required")]
        public string U_Name { get; set; }
        [DisplayName("Gender")]
        [Required(ErrorMessage = "Required")]
        public string U_Gender { get; set; }
        [DisplayName("Mobile")]
        [Required(ErrorMessage = "Required")]
        public string U_Mobile { get; set; }
        [DisplayName("Email")]
        [Required(ErrorMessage = "Required")]
        public string U_Email { get; set; }
        [DisplayName("Password")]
        [Required(ErrorMessage = "Required")]
        public string U_Password { get; set; }
        [DisplayName("CNIC")]
        [Required(ErrorMessage = "Required")]
        public string U_CNIC { get; set; }
        public Nullable<int> C_Id { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_Hostel_Booking> tbl_Hostel_Booking { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_Hostel_Detail> tbl_Hostel_Detail { get; set; }
        public virtual tbl_User_Category tbl_User_Category { get; set; }
    }
}
