//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FYP.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;

    public partial class tbl_Hostel_Images
    {
        [DisplayName("Image ID")]
        
        public int I_Id { get; set; }
        [DisplayName("Image")]
        
        public string I_Name { get; set; }
        public Nullable<int> H_Id { get; set; }
    
        public virtual tbl_Hostel_Detail tbl_Hostel_Detail { get; set; }
    }
}
